# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(951, 601)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setBaseSize(QtCore.QSize(0, 0))
        Form.setMouseTracking(False)
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(20, 410, 401, 61))
        self.textBrowser.setObjectName("textBrowser")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(580, 530, 301, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(21, 41, 381, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBoxAl = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBoxAl.setObjectName("comboBoxAl")
        self.comboBoxAl.addItem("")
        self.comboBoxAl.setItemText(0, "GA")
        self.comboBoxAl.addItem("")
        self.comboBoxAl.addItem("")
        self.horizontalLayout.addWidget(self.comboBoxAl)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBoxIns = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBoxIns.setObjectName("comboBoxIns")
        self.comboBoxIns.addItem("")
        self.comboBoxIns.addItem("")
        self.comboBoxIns.addItem("")
        self.comboBoxIns.addItem("")
        self.comboBoxIns.addItem("")
        self.comboBoxIns.addItem("")
        self.comboBoxIns.addItem("")
        self.comboBoxIns.addItem("")
        self.comboBoxIns.addItem("")
        self.comboBoxIns.addItem("")
        self.comboBoxIns.addItem("")
        self.comboBoxIns.addItem("")
        self.comboBoxIns.addItem("")
        self.comboBoxIns.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBoxIns)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(60, 520, 321, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonrun = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonrun.sizePolicy().hasHeightForWidth())
        self.pushButtonrun.setSizePolicy(sizePolicy)
        self.pushButtonrun.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButtonrun.setStyleSheet("#pushButtonrun{\n"
"border-radius:10px;\n"
"background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#pushButtonrun:hover{\n"
"    \n"
"    background-color: rgb(85, 85, 255);\n"
"}")
        self.pushButtonrun.setIconSize(QtCore.QSize(16, 16))
        self.pushButtonrun.setObjectName("pushButtonrun")
        self.horizontalLayout_3.addWidget(self.pushButtonrun)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButtonclear = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonclear.sizePolicy().hasHeightForWidth())
        self.pushButtonclear.setSizePolicy(sizePolicy)
        self.pushButtonclear.setStyleSheet("#pushButtonclear{\n"
"border-radius:10px;\n"
"background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#pushButtonclear:hover{\n"
"    \n"
"    background-color: rgb(85, 85, 255);\n"
"}")
        self.pushButtonclear.setObjectName("pushButtonclear")
        self.horizontalLayout_3.addWidget(self.pushButtonclear)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButtonexit = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonexit.sizePolicy().hasHeightForWidth())
        self.pushButtonexit.setSizePolicy(sizePolicy)
        self.pushButtonexit.setStyleSheet("#pushButtonexit{\n"
"border-radius:10px;\n"
"background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#pushButtonexit:hover{\n"
"    \n"
"    background-color: rgb(85, 85, 255);\n"
"}")
        self.pushButtonexit.setObjectName("pushButtonexit")
        self.horizontalLayout_3.addWidget(self.pushButtonexit)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 290, 361, 101))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_5.addWidget(self.lineEdit_2)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_7.addWidget(self.lineEdit_4)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_8.addWidget(self.lineEdit_3)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(450, 20, 461, 451))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.graphicsView = QtWidgets.QGraphicsView(self.widget1)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_3.addWidget(self.graphicsView)
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.widget1)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.verticalLayout_3.addWidget(self.graphicsView_2)

        self.retranslateUi(Form)
        self.pushButtonexit.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">输出信息......</p></body></html>"))
        self.label.setText(_translate("Form", "算法选择"))
        self.comboBoxAl.setItemText(1, _translate("Form", "PSO"))
        self.comboBoxAl.setItemText(2, _translate("Form", "GWO"))
        self.label_2.setText(_translate("Form", "算例选择"))
        self.comboBoxIns.setItemText(0, _translate("Form", "Ins0"))
        self.comboBoxIns.setItemText(1, _translate("Form", "Ins1"))
        self.comboBoxIns.setItemText(2, _translate("Form", "Ins2"))
        self.comboBoxIns.setItemText(3, _translate("Form", "Ins3"))
        self.comboBoxIns.setItemText(4, _translate("Form", "Ins4"))
        self.comboBoxIns.setItemText(5, _translate("Form", "Ins5"))
        self.comboBoxIns.setItemText(6, _translate("Form", "Ins6"))
        self.comboBoxIns.setItemText(7, _translate("Form", "Ins7"))
        self.comboBoxIns.setItemText(8, _translate("Form", "Ins8"))
        self.comboBoxIns.setItemText(9, _translate("Form", "Ins9"))
        self.comboBoxIns.setItemText(10, _translate("Form", "Ins10"))
        self.comboBoxIns.setItemText(11, _translate("Form", "Ins11"))
        self.comboBoxIns.setItemText(12, _translate("Form", "Ins12"))
        self.comboBoxIns.setItemText(13, _translate("Form", "Ins13"))
        self.pushButtonrun.setText(_translate("Form", "运行"))
        self.pushButtonclear.setText(_translate("Form", "清除"))
        self.pushButtonexit.setText(_translate("Form", "退出"))
        self.label_3.setText(_translate("Form", "种群数量"))
        self.label_4.setText(_translate("Form", "迭代次数"))
        self.label_5.setText(_translate("Form", "交叉概率"))
        self.label_6.setText(_translate("Form", "变异概率"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
